---
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - LICENSE.txt
  - vendor
  - node_modules
  - package.json
  - package-lock.json
  - eslint.config.mjs

keep_files:
  - assets/convimages

sass:
  sourcemap: never
